# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <- 4.3
    
# e.g. "anas_krystallinus"    
species.name <- "joep_van_dormoliniii"
    
# e.g. "red"    
color <- "FF6332"
    
# For list of colours available in R, see http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf
